name: Run Prediction Training

on:
  workflow_dispatch:
  schedule: # weekly (on monday) Europe/Rome (CET/CEST)
    - cron: "0 4 * * 1" # 04:00 UTC = 05:00 CET / 06:00 CEST

jobs:
  train-models:
    runs-on: ubuntu-24.04

    env:
      PYTHONUNBUFFERED: "1"
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_DB: ${{ secrets.MONGODB_DB }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
      MAIL_FROM: ${{ secrets.MAIL_FROM }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache trained artifacts
        uses: actions/cache@v4
        with:
          path: artifacts
          key: optcg-artifacts-${{ github.run_id }}
          restore-keys: |
            optcg-artifacts-

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r src/prediction/requirements.txt

      - name: Train prediction models
        run: |
          python -m src.prediction.run_train
