name: Run Queue Price Alert

on:
  schedule:
    # esegue ogni 1 ore (al minuto 0)
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  price-alert:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_DB: ${{ secrets.MONGODB_DB }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
      MAIL_FROM: ${{ secrets.MAIL_FROM }}
      TCG_CLIENT_ID: ${{ secrets.TCG_CLIENT_ID }}
      TCG_CLIENT_SECRET: ${{ secrets.TCG_CLIENT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo aiohttp python-dotenv requests
      - name: Run Queue Price Alert script
        run: |
          python -m src.mail.queueMail
